version: "3.8"

services:
  app:
    build: .
    container_name: case5-app
    ports:
      - "35000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - redis


  db:
    image: mysql:5.7
    container_name: case5-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: case5-redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
